Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -19,14 +19,23 @@ jobs:
       with:
         ssh-private-key: ${{ secrets.EC2_KEY }}
 
+    - name: Test SSH connection
+      run: |
+        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "echo 'SSH connection successful!'"
+
     - name: SSH into EC2 and deploy application
       run: |
         ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
         sudo su - << 'SUDO'
-        cd ${{ secrets.EC2_PROJECT_PATH }}
+        echo "Switched to root user."
+        cd ${{ secrets.EC2_PROJECT_PATH }} || { echo "Failed to cd into project directory"; exit 1; }
+        echo "Pulled latest code."
         git pull origin main
+        echo "Installed dependencies."
         npm install
+        echo "Started the application."
         npm run start:dev
         SUDO
         EOF
+
 
